const storyData = [
  {
    title: 'The Three Little Pigs',
    author: 'Flora Annie Steel',
    description:
      "The story of The Three Little Pigs featured here has been adapted from different sources and from childhood memory. The primary sources are English Fairy Tales, retold by Flora Annie Steel (1922) with illustrations by L. Leslie Brooke from the 1904 version. This story is featured in our Favorite Fairy Tales and Children's Stories.",
    full_story: [
      'Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. So when they were old enough, she sent them out into the world to seek their fortunes.',
      "The first little pig was very lazy. He didn't want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.",
      "The first little pig was very lazy. He didn't want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.",
      'The next day, a wolf happened to pass by the lane where the three little pigs lived; and he saw the straw house, and he smelled the pig inside. He thought the pig would make a mighty fine meal and his mouth began to water.',
      'So he knocked on the door and said: "Little pig! Little pig!Let me in! Let me in!"',
      'But the little pig saw the wolf\'s big paws through the keyhole, so he answered back:"  No! No! No! Not by the hairs on my chinny chin chin!"',
      "Then the wolf showed his teeth and said: \"Then I'll huff and I'll puff and I'll blow your house down.\"",
      'So he huffed and he puffed and he blew the house down! The wolf opened his jaws very wide and bit down as hard as he could, but the first little pig escaped and ran away to hide with the second little pig.',
      'The wolf continued down the lane and he passed by the second house made of sticks; and he saw the house, and he smelled the pigs inside, and his mouth began to water as he thought about the fine dinner they would make.',
      'So he huffed and he puffed and he blew the house down! The wolf was greedy and he tried to catch both pigs at once, but he was too greedy and got neither! His big jaws clamped down on nothing but air and the two little pigs scrambled away as fast as their little hooves would carry them.',
      'So he knocked on the door and said: "Little pigs! Little pigs! Let me in! Let me in!"',
      " But the little pigs saw the wolf's pointy ears through the keyhole, so they answered back: No! No! No! Not by the hairs on our chinny chin chin!",
      "Then the wolf showed his teeth and said: \"Then I'll huff and I'll puff and I'll blow your house down.\"",
      'So he huffed and he puffed and he blew the house down! The wolf was greedy and he tried to catch both pigs at once, but he was too greedy and got neither! His big jaws clamped down on nothing but air and the two little pigs scrambled away as fast as their little hooves would carry them.',
      "The wolf chased them down the lane and he almost caught them. But they made it to the brick house and slammed the door closed before the wolf could catch them. The three little pigs they were very frightened, they knew the wolf wanted to eat them. And that was very, very true. The wolf hadn't eaten all day and he had worked up a large appetite chasing the pigs around and now he could smell all three of them inside and he knew that the three little pigs would make a lovely feast.",
      'So he knocked on the door and said: "Little pigs! Little pigs! Let me in! Let me in!"',
      "But the little pigs saw the wolf's narrow eyes through the keyhole, so they answered back: No! No! No! Not by the hairs on our chinny chin chin!",
      "Then the wolf showed his teeth and said: \"Then I'll huff and I'll puff and I'll blow your house down.\"",
      "Well! he huffed and he puffed. He puffed and he huffed. And he huffed, huffed, and he puffed, puffed; but he could not blow the house down. At last, he was so out of breath that he couldn't huff and he couldn't puff anymore. So he stopped to rest and thought a bit.",
      'But this was too much. The wolf danced about with rage and swore he would come down the chimney and eat up the little pig for his supper. But while he was climbing on to the roof the little pig made up a blazing fire and put on a big pot full of water to boil. Then, just as the wolf was coming down the chimney, the little piggy pulled off the lid, and plop! in fell the wolf into the scalding water.',
      'So the little piggy put on the cover again, boiled the wolf up, and the three little pigs ate him for supper.'
    ],
    story_img: 's3 link here',
    on_StoryList: false
  },
  {
    title: 'Goldilocks and the Three Bears',
    author: 'Flora Annie Steel',
    description:
      "Goldilocks and the Three Bears was originally titled The Story of the Three Bears, published in the collection English Fairytales, retold by Flora Annie Steel (1922), illustrated by Arthur Rackham. We hope you think it's not too hot, not too cold, but JUST RIGHT! This story is featured in our Favorite Fairy Tales.",
    full_story: [
      'Once upon a time there were three Bears, who lived together in a house of their own, in a wood. One of them was a Little Wee Bear, and one was a Middle-sized Bear, and the other was a Great Big Bear. They had each a bowl for their porridge; a little bowl for the Little Wee Bear; and a middle-sized bowl for the Middle-sized Bear; and a great bowl for the Great Big Bear. And they had each a chair to sit in; a little chair for the Little Wee Bear; and a middle-sized chair for the Middle-sized Bear; and a great chair for the Great Big Bear. And they had each a bed to sleep in; a little bed for the Little Wee Bear; and a middle-sized bed for the Middle-sized Bear; and a great bed for the Great Big Bear.',
      'One day, after they had made the porridge for their breakfast, and poured it into their porridge-bowls, they walked out into the wood while the porridge was cooling, that they might not burn their mouths by beginning too soon, for they were polite, well-brought-up Bears. And while they were away a little girl called Goldilocks, who lived at the other side of the wood and had been sent on an errand by her mother, passed by the house, and looked in at the window. And then she peeped in at the keyhole, for she was not at all a well-brought-up little girl. Then seeing nobody in the house she lifted the latch. The door was not fastened, because the Bears were good Bears, who did nobody any harm, and never suspected that anybody would harm them. So Goldilocks opened the door and went in; and well pleased was she when she saw the porridge on the table. If she had been a well-brought-up little girl she would have waited till the Bears came home, and then, perhaps, they would have asked her to breakfast; for they were good Bears—a little rough or so, as the manner of Bears is, but for all that very good-natured and hospitable. But she was an impudent, rude little girl, and so she set about helping herself.',
      'First she tasted the porridge of the Great Big Bear, and that was too hot for her. Next she tasted the porridge of the Middle-sized Bear, but that was too cold for her. And then she went to the porridge of the Little Wee Bear, and tasted it, and that was neither too hot nor too cold, but just right, and she liked it so well that she ate it all up, every bit!',
      'Then Goldilocks, who was tired, for she had been catching butterflies instead of running on her errand, sate down in the chair of the Great Big Bear, but that was too hard for her. And then she sate down in the chair of the Middle-sized Bear, and that was too soft for her. But when she sat down in the chair of the Little Wee Bear, that was neither too hard nor too soft, but just right. So she seated herself in it, and there she sate till the bottom of the chair came out, and down she came, plump upon the ground; and that made her very cross, for she was a bad-tempered little girl.',
      'Now, being determined to rest, Goldilocks went upstairs into the bedchamber in which the Three Bears slept. And first she lay down upon the bed of the Great Big Bear, but that was too high at the head for her. And next she lay down upon the bed of the Middle-sized Bear, and that was too high at the foot for her. And then she lay down upon the bed of the Little Wee Bear, and that was neither too high at the head nor at the foot, but just right. So she covered herself up comfortably, and lay there till she fell fast asleep.',
      'By this time the Three Bears thought their porridge would be cool enough for them to eat it properly; so they came home to breakfast. Now careless Goldilocks had left the spoon of the Great Big Bear standing in his porridge.',
      '"SOMEBODY HAS BEEN AT MY PORRIDGE!" said the Great Big Bear in his great, rough, gruff voice. Then the Middle-sized Bear looked at his porridge and saw the spoon was standing in it too. "SOMEBODY HAS BEEN AT MY PORRIDGE!" said the Middle-sized Bear in his middle-sized voice. Then the Little Wee Bear looked at his, and there was the spoon in the porridge-bowl, but the porridge was all gone! "SOMEBODY HAS BEEN AT MY PORRIDGE, AND HAS EATEN IT ALL UP!" said the Little Wee Bear in his little wee voice.',
      'Upon this the Three Bears, seeing that some one had entered their house, and eaten up the Little Wee Bear\'s breakfast, began to look about them. Now the careless Goldilocks had not put the hard cushion straight when she rose from the chair of the Great Big Bear. "SOMEBODY HAS BEEN SITTING IN MY CHAIR!" said the Great Big Bear in his great, rough, gruff voice. And the careless Goldilocks had squatted down the soft cushion of the Middle-sized Bear. "SOMEBODY HAS BEEN SITTING IN MY CHAIR!" said the Middle-sized Bear in his middle-sized voice. "SOMEBODY HAS BEEN SITTING IN MY CHAIR, AND HAS SATE THE BOTTOM THROUGH!" said the Little Wee Bear in his little wee voice.',
      'Then the Three Bears thought they had better make further search in case it was a burglar, so they went upstairs into their bedchamber. Now Goldilocks had pulled the pillow of the Great Big Bear out of its place. "SOMEBODY HAS BEEN LYING IN MY BED!" said the Great Big Bear in his great, rough, gruff voice. And Goldilocks had pulled the bolster of the Middle-sized Bear out of its place. "SOMEBODY HAS BEEN LYING IN MY BED!" said the Middle-sized Bear in his middle-sized voice.',
      'But when the Little Wee Bear came to look at his bed, there was the bolster in its place! And the pillow was in its place upon the bolster! And upon the pillow——? There was Goldilocks\'s yellow head—which was not in its place, for she had no business there. "SOMEBODY HAS BEEN LYING IN MY BED,—AND HERE SHE IS STILL!" said the Little Wee Bear in his little wee voice.',
      'Now Goldilocks had heard in her sleep the great, rough, gruff voice of the Great Big Bear; but she was so fast asleep that it was no more to her than the roaring of wind, or the rumbling of thunder. And she had heard the middle-sized voice of the Middle-sized Bear, but it was only as if she had heard some one speaking in a dream. But when she heard the little wee voice of the Little Wee Bear, it was so sharp, and so shrill, that it awakened her at once. Up she started, and when she saw the Three Bears on one side of the bed, she tumbled herself out at the other, and ran to the window. Now the window was open, because the Bears, like good, tidy Bears, as they were, always opened their bedchamber window when they got up in the morning. So naughty, frightened little Goldilocks jumped; and whether she broke her neck in the fall, or ran into the wood and was lost there, or found her way out of the wood and got whipped for being a bad girl and playing truant, no one can say. But the Three Bears never saw anything more of her.'
    ],
    story_img: 's3 link here',
    on_StoryList: false
  }
];
